### ISSUE TITLE
feature request: make event_title and event_startDate available in registration form

### ISSUE THREAD

**Issue by Ernestopheles** [inspiredminds/contao-event-registration#15]
I  added these fields as hidden fileds in the registration form. So they are available for Leads.

But I did not succeed in filling these fields via a standard value (german: Standard-Wert) in the form.

I tried simple tokens and also insert-tags like ##event_title## or {{tl_calendar_events::title}}.

I have read #5 also.

Is there a solution inside your extension? If not, do you think its a good idea to publish a new extension, adding a ProcessFormDataListener which uses the method you mentioned in #5?

**Comment by fritzmg** [comment]
> So they are available for Leads.

Why are you trying to use this extension together with Leads?

**Comment by Ernestopheles** [comment]
Well, in BE I do have the registrations nearby the event, but as we are having multiple events, often recurring ones that are listed farer down, I think it is a good idea to supply the Leads View for better overview.

**Comment by Ernestopheles** [comment]
Thanks for asking the right questions. I am now also thinking about reducing the event list in BE (filter: upcoming events) or/and adding a FE list module (type "Auflistung") to list all registrations for all / all upcoming events. For the latter I could perhaps enhance the "Auflistung"-module with a possibility to join several tables (in this case I would need to join tl_calendar_events and tl_event_registration)

**Comment by fritzmg** [comment]
Regarding your request for Leads: this extension was specifically created to not be dependent on Leads and thus I consider this out of scope and you should customise it to your use case instead. There is another calendar extension that also supports event registration and specifically stores them in Leads, may be that one suits your use case better. Otherwise you can still store arbitrary additional data in Leads with its Hooks, at least in version 1.x. The upcoming version 3.x won't have such hooks/events anymore, but will probably be added later.
