### ISSUE TITLE
Waiting list and confirmed registrations

### ISSUE THREAD

**Issue by contaoacademy** [inspiredminds/contao-event-registration#31]
I am using version `1.3.6.` I do not use the waiting list feature.

However, recently (I can't say exactly when) I've always been shown the sign with the red exclamation mark and the clock in my list.  Previously, the green eye was displayed for confirmed registrations and the gray eye for unconfirmed registrations.
(see Screenshot)

I then looked at the database and noticed that from a certain point in time, all entries in the “waiting” column have the default value of “1”. The old entries still have “0”.

Is this a bug or an error in the configuration?

![screen-20241002_nsRgMH9j](https://github.com/user-attachments/assets/b1b1e0be-7e41-4405-870c-2f3e9ac4d951)
![screen-20241002_SjK0AmO1](https://github.com/user-attachments/assets/28bd6a8c-5914-4c53-a413-511bf16bcca2)
![screen-20241002_zVli4nIw](https://github.com/user-attachments/assets/62775fa4-748e-4326-8556-0e7241c02886)

**Comment by contaoacademy** [comment]
Maybe it has something to do with the fact that I have not entered a value for the maximum number of registrations?

https://github.com/inspiredminds/contao-event-registration/blob/dfd942af2a1477b7156803933858ccad22f3a8e0/src/EventRegistration.php#L99

**Comment by fritzmg** [comment]
This should be fixed in `1.3.7` for future registrations.

In order to fix the existing registrations that were put on the waiting list erroneously: you could either change it in the database manually, or temporarily set the max amount to a high number (higher than the amount of current registrations) and also enable the waiting list - then wait for up to one hour for the waiting list cron job to move these registrations from the waiting list to the regular list. After that disable the waiting list and remove the max amount again.

**Comment by contaoacademy** [comment]
❤️ Funktioniert alles wieder 😀
